In [75]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix

In [76]:
data = pd.read_csv('/content/spam_or_not_spam.csv')

In [77]:
data.head()

                                               email  label
0   date wed NUMBER aug NUMBER NUMBER NUMBER NUMB...      0
1  martin a posted tassos papadopoulos the greek ...      0
2  man threatens explosion in moscow thursday aug...      0
3  klez the virus that won t die already the most...      0
4   in adding cream to spaghetti carbonara which ...      0

In [78]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   email   2999 non-null   object
 1   label   3000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 47.0+ KB

In [79]:
data

                                                  email  label
0      date wed NUMBER aug NUMBER NUMBER NUMBER NUMB...      0
1     martin a posted tassos papadopoulos the greek ...      0
2     man threatens explosion in moscow thursday aug...      0
3     klez the virus that won t die already the most...      0
4      in adding cream to spaghetti carbonara which ...      0
...                                                 ...    ...
2995   abc s good morning america ranks it the NUMBE...      1
2996   hyperlink hyperlink hyperlink let mortgage le...      1
2997   thank you for shopping with us gifts for all ...      1
2998   the famous ebay marketing e course learn to s...      1
2999   hello this is chinese traditional 子 件 NUMBER世...      1

[3000 rows x 2 columns]

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
X_train, X_test, y_train, y_test = train_test_split(data['email'], data['label'],  test_size =0.2, random_state=1)

In [83]:
print('Number of rows in the total set: {}'.format(data.shape[0]))
print('Number of rows in the training set: {}'.format(X_train.shape[0]))
print('Number of rows in the test set: {}'.format(X_test.shape[0]))

Number of rows in the total set: 3000
Number of rows in the training set: 2400
Number of rows in the test set: 600

* The CountVectorizer method automatically converts all tokenized words to their lower case.

* It also ignores all punctuation.

In [84]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()

In [72]:
X_train.size

2400

In [86]:
X, y = X_train.fillna(' '), y_train

In [87]:
training_data = count_vector.fit_transform(X).toarray()

In [88]:
testing_data = count_vector.transform(X_test).toarray()

In [89]:
frequency_matrix = pd.DataFrame(training_data, columns = count_vector.get_feature_names())
frequency_matrix.head()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   __  ___  ____  _____  ...  造就許多人在這裡成功  連結  過濾信件教學  配信停止を希望される方はその旨を
0   0    0     0      0  ...           0   0       0                 0
1   0    0     0      0  ...           0   0       0                 0
2   0    0     0      0  ...           0   0       0                 0
3   0    0     0      0  ...           0   0       0                 0
4   0    0     0      0  ...           0   0       0                 0

[5 rows x 30959 columns]

In [90]:
training_data.shape

(2400, 30959)

In [91]:
testing_data

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [92]:
testing_data.shape

(600, 30959)

In [94]:
#Train the data
clf = LogisticRegression(random_state=0).fit(training_data, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [96]:
predict_values = clf.predict(testing_data)

In [98]:
print('Accuracy score: ', format(accuracy_score(y_test, predict_values)))

Accuracy score:  0.99